package tapd

type CustomFields struct {
	CustomFieldOne   string `url:"custom_field_one,omitempty" json:"custom_field_one,omitempty"`
	CustomFieldTwo   string `url:"custom_field_two,omitempty" json:"custom_field_two,omitempty"`
	CustomFieldThree string `url:"custom_field_three,omitempty" json:"custom_field_three,omitempty"`
	CustomFieldFour  string `url:"custom_field_four,omitempty" json:"custom_field_four,omitempty"`
	CustomFieldFive  string `url:"custom_field_five,omitempty" json:"custom_field_five,omitempty"`
	CustomFieldSix   string `url:"custom_field_six,omitempty" json:"custom_field_six,omitempty"`
	CustomFieldSeven string `url:"custom_field_seven,omitempty" json:"custom_field_seven,omitempty"`
	CustomFieldEight string `url:"custom_field_eight,omitempty" json:"custom_field_eight,omitempty"`
	CustomField9     string `url:"custom_field_9,omitempty" json:"custom_field_9,omitempty"`
	CustomField10    string `url:"custom_field_10,omitempty" json:"custom_field_10,omitempty"`
	CustomField11    string `url:"custom_field_11,omitempty" json:"custom_field_11,omitempty"`
	CustomField12    string `url:"custom_field_12,omitempty" json:"custom_field_12,omitempty"`
	CustomField13    string `url:"custom_field_13,omitempty" json:"custom_field_13,omitempty"`
	CustomField14    string `url:"custom_field_14,omitempty" json:"custom_field_14,omitempty"`
	CustomField15    string `url:"custom_field_15,omitempty" json:"custom_field_15,omitempty"`
	CustomField16    string `url:"custom_field_16,omitempty" json:"custom_field_16,omitempty"`
	CustomField17    string `url:"custom_field_17,omitempty" json:"custom_field_17,omitempty"`
	CustomField18    string `url:"custom_field_18,omitempty" json:"custom_field_18,omitempty"`
	CustomField19    string `url:"custom_field_19,omitempty" json:"custom_field_19,omitempty"`
	CustomField20    string `url:"custom_field_20,omitempty" json:"custom_field_20,omitempty"`
	CustomField21    string `url:"custom_field_21,omitempty" json:"custom_field_21,omitempty"`
	CustomField22    string `url:"custom_field_22,omitempty" json:"custom_field_22,omitempty"`
	CustomField23    string `url:"custom_field_23,omitempty" json:"custom_field_23,omitempty"`
	CustomField24    string `url:"custom_field_24,omitempty" json:"custom_field_24,omitempty"`
	CustomField25    string `url:"custom_field_25,omitempty" json:"custom_field_25,omitempty"`
	CustomField26    string `url:"custom_field_26,omitempty" json:"custom_field_26,omitempty"`
	CustomField27    string `url:"custom_field_27,omitempty" json:"custom_field_27,omitempty"`
	CustomField28    string `url:"custom_field_28,omitempty" json:"custom_field_28,omitempty"`
	CustomField29    string `url:"custom_field_29,omitempty" json:"custom_field_29,omitempty"`
	CustomField30    string `url:"custom_field_30,omitempty" json:"custom_field_30,omitempty"`
	CustomField31    string `url:"custom_field_31,omitempty" json:"custom_field_31,omitempty"`
	CustomField32    string `url:"custom_field_32,omitempty" json:"custom_field_32,omitempty"`
	CustomField33    string `url:"custom_field_33,omitempty" json:"custom_field_33,omitempty"`
	CustomField34    string `url:"custom_field_34,omitempty" json:"custom_field_34,omitempty"`
	CustomField35    string `url:"custom_field_35,omitempty" json:"custom_field_35,omitempty"`
	CustomField36    string `url:"custom_field_36,omitempty" json:"custom_field_36,omitempty"`
	CustomField37    string `url:"custom_field_37,omitempty" json:"custom_field_37,omitempty"`
	CustomField38    string `url:"custom_field_38,omitempty" json:"custom_field_38,omitempty"`
	CustomField39    string `url:"custom_field_39,omitempty" json:"custom_field_39,omitempty"`
	CustomField40    string `url:"custom_field_40,omitempty" json:"custom_field_40,omitempty"`
	CustomField41    string `url:"custom_field_41,omitempty" json:"custom_field_41,omitempty"`
	CustomField42    string `url:"custom_field_42,omitempty" json:"custom_field_42,omitempty"`
	CustomField43    string `url:"custom_field_43,omitempty" json:"custom_field_43,omitempty"`
	CustomField44    string `url:"custom_field_44,omitempty" json:"custom_field_44,omitempty"`
	CustomField45    string `url:"custom_field_45,omitempty" json:"custom_field_45,omitempty"`
	CustomField46    string `url:"custom_field_46,omitempty" json:"custom_field_46,omitempty"`
	CustomField47    string `url:"custom_field_47,omitempty" json:"custom_field_47,omitempty"`
	CustomField48    string `url:"custom_field_48,omitempty" json:"custom_field_48,omitempty"`
	CustomField49    string `url:"custom_field_49,omitempty" json:"custom_field_49,omitempty"`
	CustomField50    string `url:"custom_field_50,omitempty" json:"custom_field_50,omitempty"`
	CustomField51    string `url:"custom_field_51,omitempty" json:"custom_field_51,omitempty"`
	CustomField52    string `url:"custom_field_52,omitempty" json:"custom_field_52,omitempty"`
	CustomField53    string `url:"custom_field_53,omitempty" json:"custom_field_53,omitempty"`
	CustomField54    string `url:"custom_field_54,omitempty" json:"custom_field_54,omitempty"`
	CustomField55    string `url:"custom_field_55,omitempty" json:"custom_field_55,omitempty"`
	CustomField56    string `url:"custom_field_56,omitempty" json:"custom_field_56,omitempty"`
	CustomField57    string `url:"custom_field_57,omitempty" json:"custom_field_57,omitempty"`
	CustomField58    string `url:"custom_field_58,omitempty" json:"custom_field_58,omitempty"`
	CustomField59    string `url:"custom_field_59,omitempty" json:"custom_field_59,omitempty"`
	CustomField60    string `url:"custom_field_60,omitempty" json:"custom_field_60,omitempty"`
	CustomField61    string `url:"custom_field_61,omitempty" json:"custom_field_61,omitempty"`
	CustomField62    string `url:"custom_field_62,omitempty" json:"custom_field_62,omitempty"`
	CustomField63    string `url:"custom_field_63,omitempty" json:"custom_field_63,omitempty"`
	CustomField64    string `url:"custom_field_64,omitempty" json:"custom_field_64,omitempty"`
	CustomField65    string `url:"custom_field_65,omitempty" json:"custom_field_65,omitempty"`
	CustomField66    string `url:"custom_field_66,omitempty" json:"custom_field_66,omitempty"`
	CustomField67    string `url:"custom_field_67,omitempty" json:"custom_field_67,omitempty"`
	CustomField68    string `url:"custom_field_68,omitempty" json:"custom_field_68,omitempty"`
	CustomField69    string `url:"custom_field_69,omitempty" json:"custom_field_69,omitempty"`
	CustomField70    string `url:"custom_field_70,omitempty" json:"custom_field_70,omitempty"`
	CustomField71    string `url:"custom_field_71,omitempty" json:"custom_field_71,omitempty"`
	CustomField72    string `url:"custom_field_72,omitempty" json:"custom_field_72,omitempty"`
	CustomField73    string `url:"custom_field_73,omitempty" json:"custom_field_73,omitempty"`
	CustomField74    string `url:"custom_field_74,omitempty" json:"custom_field_74,omitempty"`
	CustomField75    string `url:"custom_field_75,omitempty" json:"custom_field_75,omitempty"`
	CustomField76    string `url:"custom_field_76,omitempty" json:"custom_field_76,omitempty"`
	CustomField77    string `url:"custom_field_77,omitempty" json:"custom_field_77,omitempty"`
	CustomField78    string `url:"custom_field_78,omitempty" json:"custom_field_78,omitempty"`
	CustomField79    string `url:"custom_field_79,omitempty" json:"custom_field_79,omitempty"`
	CustomField80    string `url:"custom_field_80,omitempty" json:"custom_field_80,omitempty"`
	CustomField81    string `url:"custom_field_81,omitempty" json:"custom_field_81,omitempty"`
	CustomField82    string `url:"custom_field_82,omitempty" json:"custom_field_82,omitempty"`
	CustomField83    string `url:"custom_field_83,omitempty" json:"custom_field_83,omitempty"`
	CustomField84    string `url:"custom_field_84,omitempty" json:"custom_field_84,omitempty"`
	CustomField85    string `url:"custom_field_85,omitempty" json:"custom_field_85,omitempty"`
	CustomField86    string `url:"custom_field_86,omitempty" json:"custom_field_86,omitempty"`
	CustomField87    string `url:"custom_field_87,omitempty" json:"custom_field_87,omitempty"`
	CustomField88    string `url:"custom_field_88,omitempty" json:"custom_field_88,omitempty"`
	CustomField89    string `url:"custom_field_89,omitempty" json:"custom_field_89,omitempty"`
	CustomField90    string `url:"custom_field_90,omitempty" json:"custom_field_90,omitempty"`
	CustomField91    string `url:"custom_field_91,omitempty" json:"custom_field_91,omitempty"`
	CustomField92    string `url:"custom_field_92,omitempty" json:"custom_field_92,omitempty"`
	CustomField93    string `url:"custom_field_93,omitempty" json:"custom_field_93,omitempty"`
	CustomField94    string `url:"custom_field_94,omitempty" json:"custom_field_94,omitempty"`
	CustomField95    string `url:"custom_field_95,omitempty" json:"custom_field_95,omitempty"`
	CustomField96    string `url:"custom_field_96,omitempty" json:"custom_field_96,omitempty"`
	CustomField97    string `url:"custom_field_97,omitempty" json:"custom_field_97,omitempty"`
	CustomField98    string `url:"custom_field_98,omitempty" json:"custom_field_98,omitempty"`
	CustomField99    string `url:"custom_field_99,omitempty" json:"custom_field_99,omitempty"`
	CustomField100   string `url:"custom_field_100,omitempty" json:"custom_field_100,omitempty"`
	CustomField101   string `url:"custom_field_101,omitempty" json:"custom_field_101,omitempty"`
	CustomField102   string `url:"custom_field_102,omitempty" json:"custom_field_102,omitempty"`
	CustomField103   string `url:"custom_field_103,omitempty" json:"custom_field_103,omitempty"`
	CustomField104   string `url:"custom_field_104,omitempty" json:"custom_field_104,omitempty"`
	CustomField105   string `url:"custom_field_105,omitempty" json:"custom_field_105,omitempty"`
	CustomField106   string `url:"custom_field_106,omitempty" json:"custom_field_106,omitempty"`
	CustomField107   string `url:"custom_field_107,omitempty" json:"custom_field_107,omitempty"`
	CustomField108   string `url:"custom_field_108,omitempty" json:"custom_field_108,omitempty"`
	CustomField109   string `url:"custom_field_109,omitempty" json:"custom_field_109,omitempty"`
	CustomField110   string `url:"custom_field_110,omitempty" json:"custom_field_110,omitempty"`
	CustomField111   string `url:"custom_field_111,omitempty" json:"custom_field_111,omitempty"`
	CustomField112   string `url:"custom_field_112,omitempty" json:"custom_field_112,omitempty"`
	CustomField113   string `url:"custom_field_113,omitempty" json:"custom_field_113,omitempty"`
	CustomField114   string `url:"custom_field_114,omitempty" json:"custom_field_114,omitempty"`
	CustomField115   string `url:"custom_field_115,omitempty" json:"custom_field_115,omitempty"`
	CustomField116   string `url:"custom_field_116,omitempty" json:"custom_field_116,omitempty"`
	CustomField117   string `url:"custom_field_117,omitempty" json:"custom_field_117,omitempty"`
	CustomField118   string `url:"custom_field_118,omitempty" json:"custom_field_118,omitempty"`
	CustomField119   string `url:"custom_field_119,omitempty" json:"custom_field_119,omitempty"`
	CustomField120   string `url:"custom_field_120,omitempty" json:"custom_field_120,omitempty"`
	CustomField121   string `url:"custom_field_121,omitempty" json:"custom_field_121,omitempty"`
	CustomField122   string `url:"custom_field_122,omitempty" json:"custom_field_122,omitempty"`
	CustomField123   string `url:"custom_field_123,omitempty" json:"custom_field_123,omitempty"`
	CustomField124   string `url:"custom_field_124,omitempty" json:"custom_field_124,omitempty"`
	CustomField125   string `url:"custom_field_125,omitempty" json:"custom_field_125,omitempty"`
	CustomField126   string `url:"custom_field_126,omitempty" json:"custom_field_126,omitempty"`
	CustomField127   string `url:"custom_field_127,omitempty" json:"custom_field_127,omitempty"`
	CustomField128   string `url:"custom_field_128,omitempty" json:"custom_field_128,omitempty"`
	CustomField129   string `url:"custom_field_129,omitempty" json:"custom_field_129,omitempty"`
	CustomField130   string `url:"custom_field_130,omitempty" json:"custom_field_130,omitempty"`
	CustomField131   string `url:"custom_field_131,omitempty" json:"custom_field_131,omitempty"`
	CustomField132   string `url:"custom_field_132,omitempty" json:"custom_field_132,omitempty"`
	CustomField133   string `url:"custom_field_133,omitempty" json:"custom_field_133,omitempty"`
	CustomField134   string `url:"custom_field_134,omitempty" json:"custom_field_134,omitempty"`
	CustomField135   string `url:"custom_field_135,omitempty" json:"custom_field_135,omitempty"`
	CustomField136   string `url:"custom_field_136,omitempty" json:"custom_field_136,omitempty"`
	CustomField137   string `url:"custom_field_137,omitempty" json:"custom_field_137,omitempty"`
	CustomField138   string `url:"custom_field_138,omitempty" json:"custom_field_138,omitempty"`
	CustomField139   string `url:"custom_field_139,omitempty" json:"custom_field_139,omitempty"`
	CustomField140   string `url:"custom_field_140,omitempty" json:"custom_field_140,omitempty"`
	CustomField141   string `url:"custom_field_141,omitempty" json:"custom_field_141,omitempty"`
	CustomField142   string `url:"custom_field_142,omitempty" json:"custom_field_142,omitempty"`
	CustomField143   string `url:"custom_field_143,omitempty" json:"custom_field_143,omitempty"`
	CustomField144   string `url:"custom_field_144,omitempty" json:"custom_field_144,omitempty"`
	CustomField145   string `url:"custom_field_145,omitempty" json:"custom_field_145,omitempty"`
	CustomField146   string `url:"custom_field_146,omitempty" json:"custom_field_146,omitempty"`
	CustomField147   string `url:"custom_field_147,omitempty" json:"custom_field_147,omitempty"`
	CustomField148   string `url:"custom_field_148,omitempty" json:"custom_field_148,omitempty"`
	CustomField149   string `url:"custom_field_149,omitempty" json:"custom_field_149,omitempty"`
	CustomField150   string `url:"custom_field_150,omitempty" json:"custom_field_150,omitempty"`
	CustomField151   string `url:"custom_field_151,omitempty" json:"custom_field_151,omitempty"`
	CustomField152   string `url:"custom_field_152,omitempty" json:"custom_field_152,omitempty"`
	CustomField153   string `url:"custom_field_153,omitempty" json:"custom_field_153,omitempty"`
	CustomField154   string `url:"custom_field_154,omitempty" json:"custom_field_154,omitempty"`
	CustomField155   string `url:"custom_field_155,omitempty" json:"custom_field_155,omitempty"`
	CustomField156   string `url:"custom_field_156,omitempty" json:"custom_field_156,omitempty"`
	CustomField157   string `url:"custom_field_157,omitempty" json:"custom_field_157,omitempty"`
	CustomField158   string `url:"custom_field_158,omitempty" json:"custom_field_158,omitempty"`
	CustomField159   string `url:"custom_field_159,omitempty" json:"custom_field_159,omitempty"`
	CustomField160   string `url:"custom_field_160,omitempty" json:"custom_field_160,omitempty"`
	CustomField161   string `url:"custom_field_161,omitempty" json:"custom_field_161,omitempty"`
	CustomField162   string `url:"custom_field_162,omitempty" json:"custom_field_162,omitempty"`
	CustomField163   string `url:"custom_field_163,omitempty" json:"custom_field_163,omitempty"`
	CustomField164   string `url:"custom_field_164,omitempty" json:"custom_field_164,omitempty"`
	CustomField165   string `url:"custom_field_165,omitempty" json:"custom_field_165,omitempty"`
	CustomField166   string `url:"custom_field_166,omitempty" json:"custom_field_166,omitempty"`
	CustomField167   string `url:"custom_field_167,omitempty" json:"custom_field_167,omitempty"`
	CustomField168   string `url:"custom_field_168,omitempty" json:"custom_field_168,omitempty"`
	CustomField169   string `url:"custom_field_169,omitempty" json:"custom_field_169,omitempty"`
	CustomField170   string `url:"custom_field_170,omitempty" json:"custom_field_170,omitempty"`
	CustomField171   string `url:"custom_field_171,omitempty" json:"custom_field_171,omitempty"`
	CustomField172   string `url:"custom_field_172,omitempty" json:"custom_field_172,omitempty"`
	CustomField173   string `url:"custom_field_173,omitempty" json:"custom_field_173,omitempty"`
	CustomField174   string `url:"custom_field_174,omitempty" json:"custom_field_174,omitempty"`
	CustomField175   string `url:"custom_field_175,omitempty" json:"custom_field_175,omitempty"`
	CustomField176   string `url:"custom_field_176,omitempty" json:"custom_field_176,omitempty"`
	CustomField177   string `url:"custom_field_177,omitempty" json:"custom_field_177,omitempty"`
	CustomField178   string `url:"custom_field_178,omitempty" json:"custom_field_178,omitempty"`
	CustomField179   string `url:"custom_field_179,omitempty" json:"custom_field_179,omitempty"`
	CustomField180   string `url:"custom_field_180,omitempty" json:"custom_field_180,omitempty"`
	CustomField181   string `url:"custom_field_181,omitempty" json:"custom_field_181,omitempty"`
	CustomField182   string `url:"custom_field_182,omitempty" json:"custom_field_182,omitempty"`
	CustomField183   string `url:"custom_field_183,omitempty" json:"custom_field_183,omitempty"`
	CustomField184   string `url:"custom_field_184,omitempty" json:"custom_field_184,omitempty"`
	CustomField185   string `url:"custom_field_185,omitempty" json:"custom_field_185,omitempty"`
	CustomField186   string `url:"custom_field_186,omitempty" json:"custom_field_186,omitempty"`
	CustomField187   string `url:"custom_field_187,omitempty" json:"custom_field_187,omitempty"`
	CustomField188   string `url:"custom_field_188,omitempty" json:"custom_field_188,omitempty"`
	CustomField189   string `url:"custom_field_189,omitempty" json:"custom_field_189,omitempty"`
	CustomField190   string `url:"custom_field_190,omitempty" json:"custom_field_190,omitempty"`
	CustomField191   string `url:"custom_field_191,omitempty" json:"custom_field_191,omitempty"`
	CustomField192   string `url:"custom_field_192,omitempty" json:"custom_field_192,omitempty"`
	CustomField193   string `url:"custom_field_193,omitempty" json:"custom_field_193,omitempty"`
	CustomField194   string `url:"custom_field_194,omitempty" json:"custom_field_194,omitempty"`
	CustomField195   string `url:"custom_field_195,omitempty" json:"custom_field_195,omitempty"`
	CustomField196   string `url:"custom_field_196,omitempty" json:"custom_field_196,omitempty"`
	CustomField197   string `url:"custom_field_197,omitempty" json:"custom_field_197,omitempty"`
	CustomField198   string `url:"custom_field_198,omitempty" json:"custom_field_198,omitempty"`
	CustomField199   string `url:"custom_field_199,omitempty" json:"custom_field_199,omitempty"`
	CustomField200   string `url:"custom_field_200,omitempty" json:"custom_field_200,omitempty"`
}

type CustomPlanFields struct {
	CustomPlanField1  string `url:"custom_plan_field_1,omitempty" json:"custom_plan_field_1,omitempty"`
	CustomPlanField2  string `url:"custom_plan_field_2,omitempty" json:"custom_plan_field_2,omitempty"`
	CustomPlanField3  string `url:"custom_plan_field_3,omitempty" json:"custom_plan_field_3,omitempty"`
	CustomPlanField4  string `url:"custom_plan_field_4,omitempty" json:"custom_plan_field_4,omitempty"`
	CustomPlanField5  string `url:"custom_plan_field_5,omitempty" json:"custom_plan_field_5,omitempty"`
	CustomPlanField6  string `url:"custom_plan_field_6,omitempty" json:"custom_plan_field_6,omitempty"`
	CustomPlanField7  string `url:"custom_plan_field_7,omitempty" json:"custom_plan_field_7,omitempty"`
	CustomPlanField8  string `url:"custom_plan_field_8,omitempty" json:"custom_plan_field_8,omitempty"`
	CustomPlanField9  string `url:"custom_plan_field_9,omitempty" json:"custom_plan_field_9,omitempty"`
	CustomPlanField10 string `url:"custom_plan_field_10,omitempty" json:"custom_plan_field_10,omitempty"`
}

type CustomFieldsRequest struct {
	CustomFieldOne   *string `url:"custom_field_one,omitempty" json:"custom_field_one,omitempty"`
	CustomFieldTwo   *string `url:"custom_field_two,omitempty" json:"custom_field_two,omitempty"`
	CustomFieldThree *string `url:"custom_field_three,omitempty" json:"custom_field_three,omitempty"`
	CustomFieldFour  *string `url:"custom_field_four,omitempty" json:"custom_field_four,omitempty"`
	CustomFieldFive  *string `url:"custom_field_five,omitempty" json:"custom_field_five,omitempty"`
	CustomFieldSix   *string `url:"custom_field_six,omitempty" json:"custom_field_six,omitempty"`
	CustomFieldSeven *string `url:"custom_field_seven,omitempty" json:"custom_field_seven,omitempty"`
	CustomFieldEight *string `url:"custom_field_eight,omitempty" json:"custom_field_eight,omitempty"`
	CustomField9     *string `url:"custom_field_9,omitempty" json:"custom_field_9,omitempty"`
	CustomField10    *string `url:"custom_field_10,omitempty" json:"custom_field_10,omitempty"`
	CustomField11    *string `url:"custom_field_11,omitempty" json:"custom_field_11,omitempty"`
	CustomField12    *string `url:"custom_field_12,omitempty" json:"custom_field_12,omitempty"`
	CustomField13    *string `url:"custom_field_13,omitempty" json:"custom_field_13,omitempty"`
	CustomField14    *string `url:"custom_field_14,omitempty" json:"custom_field_14,omitempty"`
	CustomField15    *string `url:"custom_field_15,omitempty" json:"custom_field_15,omitempty"`
	CustomField16    *string `url:"custom_field_16,omitempty" json:"custom_field_16,omitempty"`
	CustomField17    *string `url:"custom_field_17,omitempty" json:"custom_field_17,omitempty"`
	CustomField18    *string `url:"custom_field_18,omitempty" json:"custom_field_18,omitempty"`
	CustomField19    *string `url:"custom_field_19,omitempty" json:"custom_field_19,omitempty"`
	CustomField20    *string `url:"custom_field_20,omitempty" json:"custom_field_20,omitempty"`
	CustomField21    *string `url:"custom_field_21,omitempty" json:"custom_field_21,omitempty"`
	CustomField22    *string `url:"custom_field_22,omitempty" json:"custom_field_22,omitempty"`
	CustomField23    *string `url:"custom_field_23,omitempty" json:"custom_field_23,omitempty"`
	CustomField24    *string `url:"custom_field_24,omitempty" json:"custom_field_24,omitempty"`
	CustomField25    *string `url:"custom_field_25,omitempty" json:"custom_field_25,omitempty"`
	CustomField26    *string `url:"custom_field_26,omitempty" json:"custom_field_26,omitempty"`
	CustomField27    *string `url:"custom_field_27,omitempty" json:"custom_field_27,omitempty"`
	CustomField28    *string `url:"custom_field_28,omitempty" json:"custom_field_28,omitempty"`
	CustomField29    *string `url:"custom_field_29,omitempty" json:"custom_field_29,omitempty"`
	CustomField30    *string `url:"custom_field_30,omitempty" json:"custom_field_30,omitempty"`
	CustomField31    *string `url:"custom_field_31,omitempty" json:"custom_field_31,omitempty"`
	CustomField32    *string `url:"custom_field_32,omitempty" json:"custom_field_32,omitempty"`
	CustomField33    *string `url:"custom_field_33,omitempty" json:"custom_field_33,omitempty"`
	CustomField34    *string `url:"custom_field_34,omitempty" json:"custom_field_34,omitempty"`
	CustomField35    *string `url:"custom_field_35,omitempty" json:"custom_field_35,omitempty"`
	CustomField36    *string `url:"custom_field_36,omitempty" json:"custom_field_36,omitempty"`
	CustomField37    *string `url:"custom_field_37,omitempty" json:"custom_field_37,omitempty"`
	CustomField38    *string `url:"custom_field_38,omitempty" json:"custom_field_38,omitempty"`
	CustomField39    *string `url:"custom_field_39,omitempty" json:"custom_field_39,omitempty"`
	CustomField40    *string `url:"custom_field_40,omitempty" json:"custom_field_40,omitempty"`
	CustomField41    *string `url:"custom_field_41,omitempty" json:"custom_field_41,omitempty"`
	CustomField42    *string `url:"custom_field_42,omitempty" json:"custom_field_42,omitempty"`
	CustomField43    *string `url:"custom_field_43,omitempty" json:"custom_field_43,omitempty"`
	CustomField44    *string `url:"custom_field_44,omitempty" json:"custom_field_44,omitempty"`
	CustomField45    *string `url:"custom_field_45,omitempty" json:"custom_field_45,omitempty"`
	CustomField46    *string `url:"custom_field_46,omitempty" json:"custom_field_46,omitempty"`
	CustomField47    *string `url:"custom_field_47,omitempty" json:"custom_field_47,omitempty"`
	CustomField48    *string `url:"custom_field_48,omitempty" json:"custom_field_48,omitempty"`
	CustomField49    *string `url:"custom_field_49,omitempty" json:"custom_field_49,omitempty"`
	CustomField50    *string `url:"custom_field_50,omitempty" json:"custom_field_50,omitempty"`
	CustomField51    *string `url:"custom_field_51,omitempty" json:"custom_field_51,omitempty"`
	CustomField52    *string `url:"custom_field_52,omitempty" json:"custom_field_52,omitempty"`
	CustomField53    *string `url:"custom_field_53,omitempty" json:"custom_field_53,omitempty"`
	CustomField54    *string `url:"custom_field_54,omitempty" json:"custom_field_54,omitempty"`
	CustomField55    *string `url:"custom_field_55,omitempty" json:"custom_field_55,omitempty"`
	CustomField56    *string `url:"custom_field_56,omitempty" json:"custom_field_56,omitempty"`
	CustomField57    *string `url:"custom_field_57,omitempty" json:"custom_field_57,omitempty"`
	CustomField58    *string `url:"custom_field_58,omitempty" json:"custom_field_58,omitempty"`
	CustomField59    *string `url:"custom_field_59,omitempty" json:"custom_field_59,omitempty"`
	CustomField60    *string `url:"custom_field_60,omitempty" json:"custom_field_60,omitempty"`
	CustomField61    *string `url:"custom_field_61,omitempty" json:"custom_field_61,omitempty"`
	CustomField62    *string `url:"custom_field_62,omitempty" json:"custom_field_62,omitempty"`
	CustomField63    *string `url:"custom_field_63,omitempty" json:"custom_field_63,omitempty"`
	CustomField64    *string `url:"custom_field_64,omitempty" json:"custom_field_64,omitempty"`
	CustomField65    *string `url:"custom_field_65,omitempty" json:"custom_field_65,omitempty"`
	CustomField66    *string `url:"custom_field_66,omitempty" json:"custom_field_66,omitempty"`
	CustomField67    *string `url:"custom_field_67,omitempty" json:"custom_field_67,omitempty"`
	CustomField68    *string `url:"custom_field_68,omitempty" json:"custom_field_68,omitempty"`
	CustomField69    *string `url:"custom_field_69,omitempty" json:"custom_field_69,omitempty"`
	CustomField70    *string `url:"custom_field_70,omitempty" json:"custom_field_70,omitempty"`
	CustomField71    *string `url:"custom_field_71,omitempty" json:"custom_field_71,omitempty"`
	CustomField72    *string `url:"custom_field_72,omitempty" json:"custom_field_72,omitempty"`
	CustomField73    *string `url:"custom_field_73,omitempty" json:"custom_field_73,omitempty"`
	CustomField74    *string `url:"custom_field_74,omitempty" json:"custom_field_74,omitempty"`
	CustomField75    *string `url:"custom_field_75,omitempty" json:"custom_field_75,omitempty"`
	CustomField76    *string `url:"custom_field_76,omitempty" json:"custom_field_76,omitempty"`
	CustomField77    *string `url:"custom_field_77,omitempty" json:"custom_field_77,omitempty"`
	CustomField78    *string `url:"custom_field_78,omitempty" json:"custom_field_78,omitempty"`
	CustomField79    *string `url:"custom_field_79,omitempty" json:"custom_field_79,omitempty"`
	CustomField80    *string `url:"custom_field_80,omitempty" json:"custom_field_80,omitempty"`
	CustomField81    *string `url:"custom_field_81,omitempty" json:"custom_field_81,omitempty"`
	CustomField82    *string `url:"custom_field_82,omitempty" json:"custom_field_82,omitempty"`
	CustomField83    *string `url:"custom_field_83,omitempty" json:"custom_field_83,omitempty"`
	CustomField84    *string `url:"custom_field_84,omitempty" json:"custom_field_84,omitempty"`
	CustomField85    *string `url:"custom_field_85,omitempty" json:"custom_field_85,omitempty"`
	CustomField86    *string `url:"custom_field_86,omitempty" json:"custom_field_86,omitempty"`
	CustomField87    *string `url:"custom_field_87,omitempty" json:"custom_field_87,omitempty"`
	CustomField88    *string `url:"custom_field_88,omitempty" json:"custom_field_88,omitempty"`
	CustomField89    *string `url:"custom_field_89,omitempty" json:"custom_field_89,omitempty"`
	CustomField90    *string `url:"custom_field_90,omitempty" json:"custom_field_90,omitempty"`
	CustomField91    *string `url:"custom_field_91,omitempty" json:"custom_field_91,omitempty"`
	CustomField92    *string `url:"custom_field_92,omitempty" json:"custom_field_92,omitempty"`
	CustomField93    *string `url:"custom_field_93,omitempty" json:"custom_field_93,omitempty"`
	CustomField94    *string `url:"custom_field_94,omitempty" json:"custom_field_94,omitempty"`
	CustomField95    *string `url:"custom_field_95,omitempty" json:"custom_field_95,omitempty"`
	CustomField96    *string `url:"custom_field_96,omitempty" json:"custom_field_96,omitempty"`
	CustomField97    *string `url:"custom_field_97,omitempty" json:"custom_field_97,omitempty"`
	CustomField98    *string `url:"custom_field_98,omitempty" json:"custom_field_98,omitempty"`
	CustomField99    *string `url:"custom_field_99,omitempty" json:"custom_field_99,omitempty"`
	CustomField100   *string `url:"custom_field_100,omitempty" json:"custom_field_100,omitempty"`
	CustomField101   *string `url:"custom_field_101,omitempty" json:"custom_field_101,omitempty"`
	CustomField102   *string `url:"custom_field_102,omitempty" json:"custom_field_102,omitempty"`
	CustomField103   *string `url:"custom_field_103,omitempty" json:"custom_field_103,omitempty"`
	CustomField104   *string `url:"custom_field_104,omitempty" json:"custom_field_104,omitempty"`
	CustomField105   *string `url:"custom_field_105,omitempty" json:"custom_field_105,omitempty"`
	CustomField106   *string `url:"custom_field_106,omitempty" json:"custom_field_106,omitempty"`
	CustomField107   *string `url:"custom_field_107,omitempty" json:"custom_field_107,omitempty"`
	CustomField108   *string `url:"custom_field_108,omitempty" json:"custom_field_108,omitempty"`
	CustomField109   *string `url:"custom_field_109,omitempty" json:"custom_field_109,omitempty"`
	CustomField110   *string `url:"custom_field_110,omitempty" json:"custom_field_110,omitempty"`
	CustomField111   *string `url:"custom_field_111,omitempty" json:"custom_field_111,omitempty"`
	CustomField112   *string `url:"custom_field_112,omitempty" json:"custom_field_112,omitempty"`
	CustomField113   *string `url:"custom_field_113,omitempty" json:"custom_field_113,omitempty"`
	CustomField114   *string `url:"custom_field_114,omitempty" json:"custom_field_114,omitempty"`
	CustomField115   *string `url:"custom_field_115,omitempty" json:"custom_field_115,omitempty"`
	CustomField116   *string `url:"custom_field_116,omitempty" json:"custom_field_116,omitempty"`
	CustomField117   *string `url:"custom_field_117,omitempty" json:"custom_field_117,omitempty"`
	CustomField118   *string `url:"custom_field_118,omitempty" json:"custom_field_118,omitempty"`
	CustomField119   *string `url:"custom_field_119,omitempty" json:"custom_field_119,omitempty"`
	CustomField120   *string `url:"custom_field_120,omitempty" json:"custom_field_120,omitempty"`
	CustomField121   *string `url:"custom_field_121,omitempty" json:"custom_field_121,omitempty"`
	CustomField122   *string `url:"custom_field_122,omitempty" json:"custom_field_122,omitempty"`
	CustomField123   *string `url:"custom_field_123,omitempty" json:"custom_field_123,omitempty"`
	CustomField124   *string `url:"custom_field_124,omitempty" json:"custom_field_124,omitempty"`
	CustomField125   *string `url:"custom_field_125,omitempty" json:"custom_field_125,omitempty"`
	CustomField126   *string `url:"custom_field_126,omitempty" json:"custom_field_126,omitempty"`
	CustomField127   *string `url:"custom_field_127,omitempty" json:"custom_field_127,omitempty"`
	CustomField128   *string `url:"custom_field_128,omitempty" json:"custom_field_128,omitempty"`
	CustomField129   *string `url:"custom_field_129,omitempty" json:"custom_field_129,omitempty"`
	CustomField130   *string `url:"custom_field_130,omitempty" json:"custom_field_130,omitempty"`
	CustomField131   *string `url:"custom_field_131,omitempty" json:"custom_field_131,omitempty"`
	CustomField132   *string `url:"custom_field_132,omitempty" json:"custom_field_132,omitempty"`
	CustomField133   *string `url:"custom_field_133,omitempty" json:"custom_field_133,omitempty"`
	CustomField134   *string `url:"custom_field_134,omitempty" json:"custom_field_134,omitempty"`
	CustomField135   *string `url:"custom_field_135,omitempty" json:"custom_field_135,omitempty"`
	CustomField136   *string `url:"custom_field_136,omitempty" json:"custom_field_136,omitempty"`
	CustomField137   *string `url:"custom_field_137,omitempty" json:"custom_field_137,omitempty"`
	CustomField138   *string `url:"custom_field_138,omitempty" json:"custom_field_138,omitempty"`
	CustomField139   *string `url:"custom_field_139,omitempty" json:"custom_field_139,omitempty"`
	CustomField140   *string `url:"custom_field_140,omitempty" json:"custom_field_140,omitempty"`
	CustomField141   *string `url:"custom_field_141,omitempty" json:"custom_field_141,omitempty"`
	CustomField142   *string `url:"custom_field_142,omitempty" json:"custom_field_142,omitempty"`
	CustomField143   *string `url:"custom_field_143,omitempty" json:"custom_field_143,omitempty"`
	CustomField144   *string `url:"custom_field_144,omitempty" json:"custom_field_144,omitempty"`
	CustomField145   *string `url:"custom_field_145,omitempty" json:"custom_field_145,omitempty"`
	CustomField146   *string `url:"custom_field_146,omitempty" json:"custom_field_146,omitempty"`
	CustomField147   *string `url:"custom_field_147,omitempty" json:"custom_field_147,omitempty"`
	CustomField148   *string `url:"custom_field_148,omitempty" json:"custom_field_148,omitempty"`
	CustomField149   *string `url:"custom_field_149,omitempty" json:"custom_field_149,omitempty"`
	CustomField150   *string `url:"custom_field_150,omitempty" json:"custom_field_150,omitempty"`
	CustomField151   *string `url:"custom_field_151,omitempty" json:"custom_field_151,omitempty"`
	CustomField152   *string `url:"custom_field_152,omitempty" json:"custom_field_152,omitempty"`
	CustomField153   *string `url:"custom_field_153,omitempty" json:"custom_field_153,omitempty"`
	CustomField154   *string `url:"custom_field_154,omitempty" json:"custom_field_154,omitempty"`
	CustomField155   *string `url:"custom_field_155,omitempty" json:"custom_field_155,omitempty"`
	CustomField156   *string `url:"custom_field_156,omitempty" json:"custom_field_156,omitempty"`
	CustomField157   *string `url:"custom_field_157,omitempty" json:"custom_field_157,omitempty"`
	CustomField158   *string `url:"custom_field_158,omitempty" json:"custom_field_158,omitempty"`
	CustomField159   *string `url:"custom_field_159,omitempty" json:"custom_field_159,omitempty"`
	CustomField160   *string `url:"custom_field_160,omitempty" json:"custom_field_160,omitempty"`
	CustomField161   *string `url:"custom_field_161,omitempty" json:"custom_field_161,omitempty"`
	CustomField162   *string `url:"custom_field_162,omitempty" json:"custom_field_162,omitempty"`
	CustomField163   *string `url:"custom_field_163,omitempty" json:"custom_field_163,omitempty"`
	CustomField164   *string `url:"custom_field_164,omitempty" json:"custom_field_164,omitempty"`
	CustomField165   *string `url:"custom_field_165,omitempty" json:"custom_field_165,omitempty"`
	CustomField166   *string `url:"custom_field_166,omitempty" json:"custom_field_166,omitempty"`
	CustomField167   *string `url:"custom_field_167,omitempty" json:"custom_field_167,omitempty"`
	CustomField168   *string `url:"custom_field_168,omitempty" json:"custom_field_168,omitempty"`
	CustomField169   *string `url:"custom_field_169,omitempty" json:"custom_field_169,omitempty"`
	CustomField170   *string `url:"custom_field_170,omitempty" json:"custom_field_170,omitempty"`
	CustomField171   *string `url:"custom_field_171,omitempty" json:"custom_field_171,omitempty"`
	CustomField172   *string `url:"custom_field_172,omitempty" json:"custom_field_172,omitempty"`
	CustomField173   *string `url:"custom_field_173,omitempty" json:"custom_field_173,omitempty"`
	CustomField174   *string `url:"custom_field_174,omitempty" json:"custom_field_174,omitempty"`
	CustomField175   *string `url:"custom_field_175,omitempty" json:"custom_field_175,omitempty"`
	CustomField176   *string `url:"custom_field_176,omitempty" json:"custom_field_176,omitempty"`
	CustomField177   *string `url:"custom_field_177,omitempty" json:"custom_field_177,omitempty"`
	CustomField178   *string `url:"custom_field_178,omitempty" json:"custom_field_178,omitempty"`
	CustomField179   *string `url:"custom_field_179,omitempty" json:"custom_field_179,omitempty"`
	CustomField180   *string `url:"custom_field_180,omitempty" json:"custom_field_180,omitempty"`
	CustomField181   *string `url:"custom_field_181,omitempty" json:"custom_field_181,omitempty"`
	CustomField182   *string `url:"custom_field_182,omitempty" json:"custom_field_182,omitempty"`
	CustomField183   *string `url:"custom_field_183,omitempty" json:"custom_field_183,omitempty"`
	CustomField184   *string `url:"custom_field_184,omitempty" json:"custom_field_184,omitempty"`
	CustomField185   *string `url:"custom_field_185,omitempty" json:"custom_field_185,omitempty"`
	CustomField186   *string `url:"custom_field_186,omitempty" json:"custom_field_186,omitempty"`
	CustomField187   *string `url:"custom_field_187,omitempty" json:"custom_field_187,omitempty"`
	CustomField188   *string `url:"custom_field_188,omitempty" json:"custom_field_188,omitempty"`
	CustomField189   *string `url:"custom_field_189,omitempty" json:"custom_field_189,omitempty"`
	CustomField190   *string `url:"custom_field_190,omitempty" json:"custom_field_190,omitempty"`
	CustomField191   *string `url:"custom_field_191,omitempty" json:"custom_field_191,omitempty"`
	CustomField192   *string `url:"custom_field_192,omitempty" json:"custom_field_192,omitempty"`
	CustomField193   *string `url:"custom_field_193,omitempty" json:"custom_field_193,omitempty"`
	CustomField194   *string `url:"custom_field_194,omitempty" json:"custom_field_194,omitempty"`
	CustomField195   *string `url:"custom_field_195,omitempty" json:"custom_field_195,omitempty"`
	CustomField196   *string `url:"custom_field_196,omitempty" json:"custom_field_196,omitempty"`
	CustomField197   *string `url:"custom_field_197,omitempty" json:"custom_field_197,omitempty"`
	CustomField198   *string `url:"custom_field_198,omitempty" json:"custom_field_198,omitempty"`
	CustomField199   *string `url:"custom_field_199,omitempty" json:"custom_field_199,omitempty"`
	CustomField200   *string `url:"custom_field_200,omitempty" json:"custom_field_200,omitempty"`
}

type CustomPlanFieldsRequest struct {
	CustomPlanField1  *string `url:"custom_plan_field_1,omitempty" json:"custom_plan_field_1,omitempty"`
	CustomPlanField2  *string `url:"custom_plan_field_2,omitempty" json:"custom_plan_field_2,omitempty"`
	CustomPlanField3  *string `url:"custom_plan_field_3,omitempty" json:"custom_plan_field_3,omitempty"`
	CustomPlanField4  *string `url:"custom_plan_field_4,omitempty" json:"custom_plan_field_4,omitempty"`
	CustomPlanField5  *string `url:"custom_plan_field_5,omitempty" json:"custom_plan_field_5,omitempty"`
	CustomPlanField6  *string `url:"custom_plan_field_6,omitempty" json:"custom_plan_field_6,omitempty"`
	CustomPlanField7  *string `url:"custom_plan_field_7,omitempty" json:"custom_plan_field_7,omitempty"`
	CustomPlanField8  *string `url:"custom_plan_field_8,omitempty" json:"custom_plan_field_8,omitempty"`
	CustomPlanField9  *string `url:"custom_plan_field_9,omitempty" json:"custom_plan_field_9,omitempty"`
	CustomPlanField10 *string `url:"custom_plan_field_10,omitempty" json:"custom_plan_field_10,omitempty"`
}
