package webhook

// StoryCreateEvent represents the story create event.
type StoryCreateEvent struct {
	Event           Event  `json:"event,omitempty"`
	EventFrom       string `json:"event_from,omitempty"`
	Referer         string `json:"referer,omitempty"`
	WorkspaceID     string `json:"workspace_id,omitempty"`
	CurrentUser     string `json:"current_user,omitempty"`
	ID              string `json:"id,omitempty"`
	Name            string `json:"name,omitempty"`
	Description     string `json:"description,omitempty"`
	DescriptionType string `json:"description_type,omitempty"`
	Owner           string `json:"owner,omitempty"`
	Begin           string `json:"begin,omitempty"`
	Due             string `json:"due,omitempty"`
	Creator         string `json:"creator,omitempty"`
	Priority        string `json:"priority,omitempty"`
	WorkitemTypeID  string `json:"workitem_type_id,omitempty"`
	Status          string `json:"status,omitempty"`
	TemplatedID     string `json:"templated_id,omitempty"`
	EntityType      string `json:"entity_type,omitempty"`
	Remain          string `json:"remain,omitempty"`
	ParentID        string `json:"parent_id,omitempty"`
	AncestorID      string `json:"ancestor_id,omitempty"`
	ChildrenID      string `json:"children_id,omitempty"`
	Secret          string `json:"secret,omitempty"`
	RioToken        string `json:"rio_token,omitempty"`
	DevProxyHost    string `json:"devproxy_host,omitempty"`
	QueueID         string `json:"queue_id,omitempty"`
	EventID         string `json:"event_id,omitempty"`
	Created         string `json:"created,omitempty"`
}

// StoryUpdateEvent represents the story update event.
type StoryUpdateEvent struct {
	Event        Event             `json:"event,omitempty"`
	EventFrom    string            `json:"event_from,omitempty"`
	Referer      string            `json:"referer,omitempty"`
	WorkspaceID  string            `json:"workspace_id,omitempty"`
	CurrentUser  string            `json:"current_user,omitempty"`
	ID           string            `json:"id,omitempty"`
	ChangeFields EventChangeFields `json:"change_fields,omitempty"`
	Secret       string            `json:"secret,omitempty"`
	RioToken     string            `json:"rio_token,omitempty"`
	DevProxyHost string            `json:"devproxy_host,omitempty"`
	QueueID      string            `json:"queue_id,omitempty"`
	EventID      string            `json:"event_id,omitempty"`
	Created      string            `json:"created,omitempty"`

	StoryUpdateEventOldFields
	StoryUpdateEventNewFields
}

type StoryUpdateEventOldFields struct {
	ID                  *string `json:"old_id,omitempty"`
	Name                *string `json:"old_name,omitempty"`
	Description         *string `json:"old_description,omitempty"`
	MarkdownDescription *string `json:"old_markdown_description,omitempty"`
	DescriptionType     *string `json:"old_description_type,omitempty"`
	Creator             *string `json:"old_creator,omitempty"`
	Created             *string `json:"old_created,omitempty"`
	Modified            *string `json:"old_modified,omitempty"`
	ParentID            *string `json:"old_parent_id,omitempty"`
	ChildrenID          *string `json:"old_children_id,omitempty"`
	AncestorID          *string `json:"old_ancestor_id,omitempty"`
	Path                *string `json:"old_path,omitempty"`
	Level               *string `json:"old_level,omitempty"`
	WorkspaceID         *string `json:"old_workspace_id,omitempty"`
	Status              *string `json:"old_status,omitempty"`
	Flows               *string `json:"old_flows,omitempty"`
	Priority            *string `json:"old_priority,omitempty"`
	Owner               *string `json:"old_owner,omitempty"`
	Cc                  *string `json:"old_cc,omitempty"`
	Begin               *string `json:"old_begin,omitempty"`
	Due                 *string `json:"old_due,omitempty"`
	Source              *string `json:"old_source,omitempty"`
	WorkitemID          *string `json:"old_workitem_id,omitempty"`
	StoryID             *string `json:"old_story_id,omitempty"`
	IterationID         *string `json:"old_iteration_id,omitempty"`
	SubStrace           *string `json:"old_substrace,omitempty"`
	Completed           *string `json:"old_completed,omitempty"`
	Effort              *string `json:"old_effort,omitempty"`
	EffortCompleted     *string `json:"old_effort_completed,omitempty"`
	EffortTotal         *string `json:"old_effort_total,omitempty"`
	Exceed              *string `json:"old_exceed,omitempty"`
	Remain              *string `json:"old_remain,omitempty"`
	Progress            *string `json:"old_progress,omitempty"`
	EntityType          *string `json:"old_entity_type,omitempty"`
	CustomFieldOne      *string `json:"old_custom_field_one,omitempty"`
	CustomFieldTwo      *string `json:"old_custom_field_two,omitempty"`
	CustomFieldThree    *string `json:"old_custom_field_three,omitempty"`
	CustomFieldFour     *string `json:"old_custom_field_four,omitempty"`
	CustomFieldFive     *string `json:"old_custom_field_five,omitempty"`
	CustomFieldSix      *string `json:"old_custom_field_six,omitempty"`
	CustomFieldSeven    *string `json:"old_custom_field_seven,omitempty"`
	CustomFieldEight    *string `json:"old_custom_field_eight,omitempty"`
	CustomField9        *string `json:"old_custom_field_9,omitempty"`
	CustomField10       *string `json:"old_custom_field_10,omitempty"`
	CustomField11       *string `json:"old_custom_field_11,omitempty"`
	CustomField12       *string `json:"old_custom_field_12,omitempty"`
	CustomField13       *string `json:"old_custom_field_13,omitempty"`
	CustomField14       *string `json:"old_custom_field_14,omitempty"`
	CustomField15       *string `json:"old_custom_field_15,omitempty"`
	CustomField16       *string `json:"old_custom_field_16,omitempty"`
	CustomField17       *string `json:"old_custom_field_17,omitempty"`
	CustomField18       *string `json:"old_custom_field_18,omitempty"`
	CustomField19       *string `json:"old_custom_field_19,omitempty"`
	CustomField20       *string `json:"old_custom_field_20,omitempty"`
	CustomField21       *string `json:"old_custom_field_21,omitempty"`
	CustomField22       *string `json:"old_custom_field_22,omitempty"`
	CustomField23       *string `json:"old_custom_field_23,omitempty"`
	CustomField24       *string `json:"old_custom_field_24,omitempty"`
	CustomField25       *string `json:"old_custom_field_25,omitempty"`
	CustomField26       *string `json:"old_custom_field_26,omitempty"`
	CustomField27       *string `json:"old_custom_field_27,omitempty"`
	CustomField28       *string `json:"old_custom_field_28,omitempty"`
	CustomField29       *string `json:"old_custom_field_29,omitempty"`
	CustomField30       *string `json:"old_custom_field_30,omitempty"`
	CustomField31       *string `json:"old_custom_field_31,omitempty"`
	CustomField32       *string `json:"old_custom_field_32,omitempty"`
	CustomField33       *string `json:"old_custom_field_33,omitempty"`
	CustomField34       *string `json:"old_custom_field_34,omitempty"`
	CustomField35       *string `json:"old_custom_field_35,omitempty"`
	CustomField36       *string `json:"old_custom_field_36,omitempty"`
	CustomField37       *string `json:"old_custom_field_37,omitempty"`
	CustomField38       *string `json:"old_custom_field_38,omitempty"`
	CustomField39       *string `json:"old_custom_field_39,omitempty"`
	CustomField40       *string `json:"old_custom_field_40,omitempty"`
	CustomField41       *string `json:"old_custom_field_41,omitempty"`
	CustomField42       *string `json:"old_custom_field_42,omitempty"`
	CustomField43       *string `json:"old_custom_field_43,omitempty"`
	CustomField44       *string `json:"old_custom_field_44,omitempty"`
	CustomField45       *string `json:"old_custom_field_45,omitempty"`
	CustomField46       *string `json:"old_custom_field_46,omitempty"`
	CustomField47       *string `json:"old_custom_field_47,omitempty"`
	CustomField48       *string `json:"old_custom_field_48,omitempty"`
	CustomField49       *string `json:"old_custom_field_49,omitempty"`
	CustomField50       *string `json:"old_custom_field_50,omitempty"`
	CustomPlanField1    *string `json:"old_custom_plan_field_1,omitempty"`
	CustomPlanField2    *string `json:"old_custom_plan_field_2,omitempty"`
	CustomPlanField3    *string `json:"old_custom_plan_field_3,omitempty"`
	CustomPlanField4    *string `json:"old_custom_plan_field_4,omitempty"`
	CustomPlanField5    *string `json:"old_custom_plan_field_5,omitempty"`
	CustomPlanField6    *string `json:"old_custom_plan_field_6,omitempty"`
	CustomPlanField7    *string `json:"old_custom_plan_field_7,omitempty"`
	CustomPlanField8    *string `json:"old_custom_plan_field_8,omitempty"`
	CustomPlanField9    *string `json:"old_custom_plan_field_9,omitempty"`
	CustomPlanField10   *string `json:"old_custom_plan_field_10,omitempty"`
	AttachmentCount     *string `json:"old_attachment_count,omitempty"`
	HasAttachment       *string `json:"old_has_attachment,omitempty"`
	Follower            *string `json:"old_follower,omitempty"`
	CreatedFrom         *string `json:"old_created_from,omitempty"`
	PredecessorCount    *string `json:"old_predecessor_count,omitempty"`
	SuccessorCount      *string `json:"old_successor_count,omitempty"`
	ReleaseID           *string `json:"old_release_id,omitempty"`
	Label               *string `json:"old_label,omitempty"`
	NewStoryID          *string `json:"old_new_story_id,omitempty"`
}

type StoryUpdateEventNewFields struct {
	ID                  *string `json:"new_id,omitempty"`
	Name                *string `json:"new_name,omitempty"`
	Description         *string `json:"new_description,omitempty"`
	MarkdownDescription *string `json:"new_markdown_description,omitempty"`
	DescriptionType     *string `json:"new_description_type,omitempty"`
	Creator             *string `json:"new_creator,omitempty"`
	Created             *string `json:"new_created,omitempty"`
	Modified            *string `json:"new_modified,omitempty"`
	ParentID            *string `json:"new_parent_id,omitempty"`
	ChildrenID          *string `json:"new_children_id,omitempty"`
	AncestorID          *string `json:"new_ancestor_id,omitempty"`
	Path                *string `json:"new_path,omitempty"`
	Level               *string `json:"new_level,omitempty"`
	WorkspaceID         *string `json:"new_workspace_id,omitempty"`
	Status              *string `json:"new_status,omitempty"`
	Flows               *string `json:"new_flows,omitempty"`
	Priority            *string `json:"new_priority,omitempty"`
	Owner               *string `json:"new_owner,omitempty"`
	Cc                  *string `json:"new_cc,omitempty"`
	Begin               *string `json:"new_begin,omitempty"`
	Due                 *string `json:"new_due,omitempty"`
	Source              *string `json:"new_source,omitempty"`
	WorkitemID          *string `json:"new_workitem_id,omitempty"`
	StoryID             *string `json:"new_story_id,omitempty"`
	IterationID         *string `json:"new_iteration_id,omitempty"`
	SubStrace           *string `json:"new_substrace,omitempty"`
	Completed           *string `json:"new_completed,omitempty"`
	Effort              *string `json:"new_effort,omitempty"`
	EffortCompleted     *string `json:"new_effort_completed,omitempty"`
	EffortTotal         *string `json:"new_effort_total,omitempty"`
	Exceed              *string `json:"new_exceed,omitempty"`
	Remain              *string `json:"new_remain,omitempty"`
	Progress            *string `json:"new_progress,omitempty"`
	EntityType          *string `json:"new_entity_type,omitempty"`
	CustomFieldOne      *string `json:"new_custom_field_one,omitempty"`
	CustomFieldTwo      *string `json:"new_custom_field_two,omitempty"`
	CustomFieldThree    *string `json:"new_custom_field_three,omitempty"`
	CustomFieldFour     *string `json:"new_custom_field_four,omitempty"`
	CustomFieldFive     *string `json:"new_custom_field_five,omitempty"`
	CustomFieldSix      *string `json:"new_custom_field_six,omitempty"`
	CustomFieldSeven    *string `json:"new_custom_field_seven,omitempty"`
	CustomFieldEight    *string `json:"new_custom_field_eight,omitempty"`
	CustomField9        *string `json:"new_custom_field_9,omitempty"`
	CustomField10       *string `json:"new_custom_field_10,omitempty"`
	CustomField11       *string `json:"new_custom_field_11,omitempty"`
	CustomField12       *string `json:"new_custom_field_12,omitempty"`
	CustomField13       *string `json:"new_custom_field_13,omitempty"`
	CustomField14       *string `json:"new_custom_field_14,omitempty"`
	CustomField15       *string `json:"new_custom_field_15,omitempty"`
	CustomField16       *string `json:"new_custom_field_16,omitempty"`
	CustomField17       *string `json:"new_custom_field_17,omitempty"`
	CustomField18       *string `json:"new_custom_field_18,omitempty"`
	CustomField19       *string `json:"new_custom_field_19,omitempty"`
	CustomField20       *string `json:"new_custom_field_20,omitempty"`
	CustomField21       *string `json:"new_custom_field_21,omitempty"`
	CustomField22       *string `json:"new_custom_field_22,omitempty"`
	CustomField23       *string `json:"new_custom_field_23,omitempty"`
	CustomField24       *string `json:"new_custom_field_24,omitempty"`
	CustomField25       *string `json:"new_custom_field_25,omitempty"`
	CustomField26       *string `json:"new_custom_field_26,omitempty"`
	CustomField27       *string `json:"new_custom_field_27,omitempty"`
	CustomField28       *string `json:"new_custom_field_28,omitempty"`
	CustomField29       *string `json:"new_custom_field_29,omitempty"`
	CustomField30       *string `json:"new_custom_field_30,omitempty"`
	CustomField31       *string `json:"new_custom_field_31,omitempty"`
	CustomField32       *string `json:"new_custom_field_32,omitempty"`
	CustomField33       *string `json:"new_custom_field_33,omitempty"`
	CustomField34       *string `json:"new_custom_field_34,omitempty"`
	CustomField35       *string `json:"new_custom_field_35,omitempty"`
	CustomField36       *string `json:"new_custom_field_36,omitempty"`
	CustomField37       *string `json:"new_custom_field_37,omitempty"`
	CustomField38       *string `json:"new_custom_field_38,omitempty"`
	CustomField39       *string `json:"new_custom_field_39,omitempty"`
	CustomField40       *string `json:"new_custom_field_40,omitempty"`
	CustomField41       *string `json:"new_custom_field_41,omitempty"`
	CustomField42       *string `json:"new_custom_field_42,omitempty"`
	CustomField43       *string `json:"new_custom_field_43,omitempty"`
	CustomField44       *string `json:"new_custom_field_44,omitempty"`
	CustomField45       *string `json:"new_custom_field_45,omitempty"`
	CustomField46       *string `json:"new_custom_field_46,omitempty"`
	CustomField47       *string `json:"new_custom_field_47,omitempty"`
	CustomField48       *string `json:"new_custom_field_48,omitempty"`
	CustomField49       *string `json:"new_custom_field_49,omitempty"`
	CustomField50       *string `json:"new_custom_field_50,omitempty"`
	CustomPlanField1    *string `json:"new_custom_plan_field_1,omitempty"`
	CustomPlanField2    *string `json:"new_custom_plan_field_2,omitempty"`
	CustomPlanField3    *string `json:"new_custom_plan_field_3,omitempty"`
	CustomPlanField4    *string `json:"new_custom_plan_field_4,omitempty"`
	CustomPlanField5    *string `json:"new_custom_plan_field_5,omitempty"`
	CustomPlanField6    *string `json:"new_custom_plan_field_6,omitempty"`
	CustomPlanField7    *string `json:"new_custom_plan_field_7,omitempty"`
	CustomPlanField8    *string `json:"new_custom_plan_field_8,omitempty"`
	CustomPlanField9    *string `json:"new_custom_plan_field_9,omitempty"`
	CustomPlanField10   *string `json:"new_custom_plan_field_10,omitempty"`
	AttachmentCount     *string `json:"new_attachment_count,omitempty"`
	HasAttachment       *string `json:"new_has_attachment,omitempty"`
	Follower            *string `json:"new_follower,omitempty"`
	CreatedFrom         *string `json:"new_created_from,omitempty"`
	PredecessorCount    *string `json:"new_predecessor_count,omitempty"`
	SuccessorCount      *string `json:"new_successor_count,omitempty"`
	ReleaseID           *string `json:"new_release_id,omitempty"`
	Label               *string `json:"new_label,omitempty"`
	NewStoryID          *string `json:"new_new_story_id,omitempty"`
}
